export enum ROUTES {
  login = '/',
  main = '/main',
  media = '/media-manager',
  all = '/show-media',
  product = '/product-manager',
  addProduct = '/add-product',
  pagedProduct = '/page-product',
  singleProduct = '/product-by-id',
  hero = '/hero',
  addHero = '/add-hero',
  getHero = '/get-hero',
  promo = '/promo',
  getPromo = '/get-promo',
  archive = '/archive',
  createArchive = '/create-archive',
  getArchive = '/get-archive',
  settings = '/settings',
  orders = '/orders',
  ordersById = '/order-id'
}
